Suggestion/egg files metadata
anchore/syft pull request #947
Opened 2022-04-12 09:47 UTC by houdini91

Suggesting enhancement to the python cataloger.
Catalog package files for legacy egg 'installed-files.txt' metadata.
For example `psycopg2` does not have linux wheel so it uses egg, then django uses `psycopg2` and so one...

[https://github.com/pypa/pip/blob/1cda23bd6bd0066ad557e4f7ca7c670744357b2b/src/pip/_internal/operations/install/legacy.py](url)

Note: It seemed that EGG `installed-files.txt` and wheel `RECORD` use paths that are relative to different base dirs.
I added a normalization flow for the `installed-fiels.txt` to the one used by `RECORD`.

* `Installed-files.txt` - relative to egg Info dir.
* `RECORD` - relative to site-packages root dir.

2022-08-15 14:07 UTC, kzantow requested changes
Hi @houdini91 -- this PR is looking pretty close but I think we'd like to see some basic tests added, would you be able to do this?

2022-08-15 14:07 UTC, kzantow commented on syft/pkg/cataloger/python/parse_wheel_egg_record.go
> +		if err != nil {
Should failure reading the `installed-files` be a critical error? The caller seems to treat it as critical, but as it wasn't even being done before maybe these should instead be warnings?

2022-09-19 18:37 UTC, spiffcs commented on syft/pkg/cataloger/python/package_cataloger.go
> +	installedFilesRef := resolver.RelativeFileByPath(metadataLocation, installedFilesPath)
discussed this as the correct method returning a single result

2022-09-19 21:08 UTC, spiffcs commented
Merged with #1217 - Thanks again for all the help on this one @houdini91!

2022-09-19 21:08 UTC, closed without merging